=== fergone03/Portfolio-de-trabajos/Primero/Lenguajes de marcas y sistemas de gestión de información/Tema 12/PRÁCTICA LENGUAJE DE MARCAS (DTD, XSD, XPATH)/1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="alumnoType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="nota">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="sexo">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Hombre"/>
                        <xs:enumeration value="Mujer"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="aprobado" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="SI"/>
                    <xs:enumeration value="NO"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="moduloType">
        <xs:sequence>
            <xs:element name="alumno" type="alumnoType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="ciclo" type="xs:IDREF" use="required"/>
        <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="cicloType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:ID" use="required"/>
                <xs:attribute name="grado">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Medio"/>
                            <xs:enumeration value="Superior"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="especialidadType">
        <xs:sequence>
            <xs:element name="ciclo" type="cicloType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ciclosType">
        <xs:sequence>
            <xs:element name="especialidad" type="especialidadType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="notasType">
        <xs:sequence>
            <xs:element name="modulo" type="moduloType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="instituto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ciclos" type="ciclosType"/>
                <xs:element name="notas" type="notasType"/>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== fergone03/Portfolio-de-trabajos/Primero/Lenguajes de marcas y sistemas de gestión de información/Tema 12/PRÁCTICA LENGUAJE DE MARCAS (DTD, XSD, XPATH)/1_xsd.xml
<instituto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1.xsd" nombre="Medac Formación">
    <ciclos>
        <especialidad nombre="Informática">
            <ciclo id="DAW" grado="Superior">
                   Desarrollo de aplicaciones Web
            </ciclo>
            <ciclo id="ASIR" grado="Superior">
                   Administración de Sistemas informáticos y Redes
            </ciclo>
            <ciclo id="SMR" grado="Medio">
                   Sistemas Microinformáticos y Redes
            </ciclo>
        </especialidad>
        <especialidad nombre="Administrativo">
            <ciclo id="GA" grado="Medio">
                   Gestión Administrativa
            </ciclo>
            <ciclo id="AF" grado="Superior">
                   Administración y Finanzas
            </ciclo>
        </especialidad>
    </ciclos>
    <notas>
        <modulo ciclo="DAW" nombre="LLMM">
            <alumno aprobado="SI">
                <nombre>Federico Ruíz</nombre>
                <nota>8</nota>
                <sexo>Hombre</sexo>
            </alumno>
            <alumno aprobado="NO">
                <nombre>Silvia Martín</nombre>
                <nota>3</nota>
                <sexo>Mujer</sexo>
            </alumno>
            <alumno aprobado="SI">
                <nombre>Manolo Chicón</nombre>
                <nota>8</nota>
                <sexo>Hombre</sexo>
            </alumno>
        </modulo>
        <modulo ciclo="DAW" nombre="PRO">
            <alumno aprobado="SI">
                <nombre>Federico Ruíz</nombre>
                <nota>9</nota>
                <sexo>Hombre</sexo>
            </alumno>
            <alumno aprobado="SI">
                <nombre>Silvia Martín</nombre>
                <nota>6</nota>
                <sexo>Mujer</sexo>
            </alumno>
            <alumno aprobado="SI">
                <nombre>Manolo Chicón</nombre>
                <nota>5</nota>
                <sexo>Hombre</sexo>
            </alumno>
        </modulo>
    </notas>
</instituto>
